---
title: "Untitled"
author: "Beate, Marcus, Jonas, Wilmer"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
First load the following libraries
```{r}
library(tidyverse)
library(tidymodels)
library(dplyr)
library(rsample)
library(ranger)
```
The data is fetched from "https://shorturl.at/crAK3". 
This dataset contains files for four wine styles: red, white, rosé, and sparkling. 
Each of these has eight columns, including the ``NumberOfRatings'' column indicating the count of people who rated the wine. 

```{r}
red <- read.csv("Red.csv")
white <- read.csv("White.csv")
rose <- read.csv("Rose.csv")
sparkling <- read.csv("Sparkling.csv")

red$Type <- "Red"
white$Type <- "White"
rose$Type <- "Rose"
sparkling$Type <- "Sparkling"

data <- rbind(red, white, rose, sparkling) %>% select(-Name); head(data)
# data <- data[complete.cases(data),]
data <- data %>%
  filter(Year != "N.V.")
```

```{r}
cell_split <- initial_split(data, prop = 1/70, strata = "Type")

train_data <- training(cell_split)
test_data <- testing(cell_split);head(train_data)
```

```{r}
rf_mod <- rand_forest(mode = "regression", trees = 1000) %>% 
          set_engine("ranger")
rf_fit <- rf_mod %>% fit(Rating ~ ., data = train_data); rf_fit
folds <- vfold_cv(train_data, v = 10)
rf_wf <-
    workflow() %>%
    add_model(rf_mod) %>%
    add_formula(Rating ~ .)
rf_fit_rs <-
    rf_wf %>%
    fit_resamples(folds)
collect_metrics(rf_fit_rs)

rf_fit <- rf_wf %>% fit(data = train_data)
```

```{r}
lm_mod <- linear_reg() %>% set_engine("lm")
lm_fit <- lm_mod %>% fit(Rating ~ ., data = train_data); tidy(lm_fit)
data <- rbind(red, white, rose, sparkling) %>% select(-Name,-Winery,-Country); head(data)
lm_wf <-
    workflow() %>%
    add_model(lm_mod) %>%
    add_formula(Rating ~ .)
lm_fit_rs <-
    lm_wf %>%
    fit_resamples(folds)
collect_metrics(lm_fit_rs)
```

```{r}

```

```{r}

```